version: "3.3"
services:
  api:
    build: backend
    ports:
      - "5000:5000"
    links:
      - postgres
    depends_on:
      - postgres
      - migrator
    environment:
      - DATABASE_URL=postgres://retail_manager:retail_manager@postgres:5432/retail_manager
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=5000
      - RUST_LOG="debug,actix_web=trace"
      - SESSION_SECRET=fdsakfljdsakliourqoewilkfldksaoidsaop
      - SESSION_NAME=retail_manager_id
      - SESSION_SECURE=false
      - SESSION_MAX_AGE_H=24
      - JWT_KEY=fsdalkorpqewipofdsafoiopureqwiod
      - JWT_EXPIRATION_H=30
      - CORS_ALLOWED_ORIGIN=http://192.168.0.112:3000
      - FRONTEND_BASE_URL=http://192.168.0.112:3000
  migrator:
    build:
      context: backend
      dockerfile: Dockerfile.migrator
    depends_on:
      - postgres
    command: ["/bin/sh", "-c", "movine init && movine up"]
    environment:
      - DATABASE_URL=postgres://retail_manager:retail_manager@postgres:5432/retail_manager
  frontend:
    build:
      context: frontend
      args:
        REACT_APP_API_URL: http://192.168.0.112:5000
        REACT_APP_DOMAIN: http://192.168.0.112:3000
        NGINX_PORT: '80'
    ports:
      - "3000:80"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=retail_manager
      - POSTGRES_PASSWORD=retail_manager
      - POSTGRES_DB=retail_manager
    volumes:
      - "postgres:/var/lib/postgresql/data"
volumes:
  postgres:
